// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/payment-api.proto

package paymentapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PaymentAPI service

func NewPaymentAPIEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PaymentAPI service

type PaymentAPIService interface {
	MakePayment(ctx context.Context, in *MakePaymentRequest, opts ...client.CallOption) (*MakePaymentResponse, error)
	GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...client.CallOption) (*GetPaymentResponse, error)
}

type paymentAPIService struct {
	c    client.Client
	name string
}

func NewPaymentAPIService(name string, c client.Client) PaymentAPIService {
	return &paymentAPIService{
		c:    c,
		name: name,
	}
}

func (c *paymentAPIService) MakePayment(ctx context.Context, in *MakePaymentRequest, opts ...client.CallOption) (*MakePaymentResponse, error) {
	req := c.c.NewRequest(c.name, "PaymentAPI.MakePayment", in)
	out := new(MakePaymentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentAPIService) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...client.CallOption) (*GetPaymentResponse, error) {
	req := c.c.NewRequest(c.name, "PaymentAPI.GetPayment", in)
	out := new(GetPaymentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PaymentAPI service

type PaymentAPIHandler interface {
	MakePayment(context.Context, *MakePaymentRequest, *MakePaymentResponse) error
	GetPayment(context.Context, *GetPaymentRequest, *GetPaymentResponse) error
}

func RegisterPaymentAPIHandler(s server.Server, hdlr PaymentAPIHandler, opts ...server.HandlerOption) error {
	type paymentAPI interface {
		MakePayment(ctx context.Context, in *MakePaymentRequest, out *MakePaymentResponse) error
		GetPayment(ctx context.Context, in *GetPaymentRequest, out *GetPaymentResponse) error
	}
	type PaymentAPI struct {
		paymentAPI
	}
	h := &paymentAPIHandler{hdlr}
	return s.Handle(s.NewHandler(&PaymentAPI{h}, opts...))
}

type paymentAPIHandler struct {
	PaymentAPIHandler
}

func (h *paymentAPIHandler) MakePayment(ctx context.Context, in *MakePaymentRequest, out *MakePaymentResponse) error {
	return h.PaymentAPIHandler.MakePayment(ctx, in, out)
}

func (h *paymentAPIHandler) GetPayment(ctx context.Context, in *GetPaymentRequest, out *GetPaymentResponse) error {
	return h.PaymentAPIHandler.GetPayment(ctx, in, out)
}
